theme = "catppuccin_macchiato"

[editor]
cursorline = true
scrolloff = 8
color-modes = true
true-color = true
undercurl = true
rulers = [80, 120]
popup-border = "all"
whitespace.render = { space = "all", tab = "all" }
